name: deploy-marketing
on:
  push:
    branches:
      - master
    paths:
      - 'marketing/**'

defaults:
    run:
      working-directory: ./marketing
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

